export const GET_ALBUMS = "GET_ALBUMS";
export const GET_PHOTOS = "GET_PHOTOS";
export const GET_ALBUMS_FAILED = "GET_ALBUMS_FAILED";
export const GET_PHOTOS_FAILED = "GET_PHOTOS_FAILED";
export const GET_ALBUMS_LOADING = "GET_ALBUMS_LOADING";
export const GET_PHOTOS_LOADING = "GET_PHOTOS_LOADING";
